### start livestub with `docker-compose up` first
### setup livestub, the third request will return 200 and the message will get accepted
POST http://localhost:7070/__set_many

{
  "when": {
    "method": "POST",
    "url": "deliver"
  },
  "then": [
    {
      "statusCode": 408,
      "body": {
        "status": ""
      }
    },
    {
      "statusCode": 425,
      "body": {
        "status": ""
      }
    },
    {
      "statusCode": 200,
      "body": {
        "status": ""
      }
    }
  ]
}
###

